spring:
  application:
    name: flyshort
  datasource:
    url: jdbc:postgresql://postgres:5432/flyshortdb
    username: flyshortuser
    password: flyshortpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  